# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangyin/nameserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangyin/nameserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangyin/nameserver/CMakeFiles /home/zhangyin/nameserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangyin/nameserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nameserver

# Build rule for target.
nameserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nameserver
.PHONY : nameserver

# fast build rule for target.
nameserver/fast:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/build
.PHONY : nameserver/fast

filetree.o: filetree.cpp.o

.PHONY : filetree.o

# target to build an object file
filetree.cpp.o:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/filetree.cpp.o
.PHONY : filetree.cpp.o

filetree.i: filetree.cpp.i

.PHONY : filetree.i

# target to preprocess a source file
filetree.cpp.i:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/filetree.cpp.i
.PHONY : filetree.cpp.i

filetree.s: filetree.cpp.s

.PHONY : filetree.s

# target to generate assembly for a file
filetree.cpp.s:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/filetree.cpp.s
.PHONY : filetree.cpp.s

nameserver.o: nameserver.cpp.o

.PHONY : nameserver.o

# target to build an object file
nameserver.cpp.o:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/nameserver.cpp.o
.PHONY : nameserver.cpp.o

nameserver.i: nameserver.cpp.i

.PHONY : nameserver.i

# target to preprocess a source file
nameserver.cpp.i:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/nameserver.cpp.i
.PHONY : nameserver.cpp.i

nameserver.s: nameserver.cpp.s

.PHONY : nameserver.s

# target to generate assembly for a file
nameserver.cpp.s:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/nameserver.cpp.s
.PHONY : nameserver.cpp.s

util.o: util.cpp.o

.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i

.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s

.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/nameserver.dir/build.make CMakeFiles/nameserver.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... nameserver"
	@echo "... edit_cache"
	@echo "... filetree.o"
	@echo "... filetree.i"
	@echo "... filetree.s"
	@echo "... nameserver.o"
	@echo "... nameserver.i"
	@echo "... nameserver.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

